jdbc:
    url: jdbc:mariadb://localhost:3306/?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&characterEncoding=UTF8&allowMultiQueries=true
    user: root
    password: 
    driver: org.mariadb.jdbc.Driver